SAREV/smart_meter-master/sm_platform/accounts/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    #path('register/activate/<uidb64>/<token>/',user_activation_view , name = 'activate'),
    path('register/',RegisterView.as_view(),name = 'register'),
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/registration/login.html' , redirect_authenticated_user = True),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'accounts/registration/logged_out.html'),name = 'logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(
                                            template_name ='accounts/registration/password_reset.html',
                                            email_template_name = 'accounts/registration/password_reset_email.html',
                                            success_url='done/'),
                            name='password_reset'),

    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(
                                            template_name ='accounts/registration/password_reset_done.html'),
                            name='password_reset_done'),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
                                            template_name ='accounts/registration/password_reset_confirm.html',
                                            success_url ='/accounts/reset/done/'),
                            name='password_reset_confirm'),

    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(
                                            template_name ='accounts/registration/password_reset_complete.html'),
                            name='password_reset_complete'),

    path('<str:username>/password_change/',
            auth_views.PasswordChangeView.as_view(template_name = "accounts/changePassword.html",
                success_url ='done/'),
                                name='password_change'),

    path('<str:username>/password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/changePasswordDone.html") ,
                                                name='password_change_done'),
    path('<str:username>/delete_account/confirm/',delete_account_confirm, name = 'delete_account_confirm' ),
    path('<str:username>/delete_account/',delete_account , name = 'delete_account'),


]

SAREV/smart_meter-master/sm_platform/manager/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'manager'

urlpatterns = [
    path('add_data/<distributerName>/<distributerPass>/<meterNumber>/<voltage>/<current>/',add_data,name ='add_data'),
    path('get_bill/<str:username>/<id>/',get_bill,name='get_bill'),
    path('check_user/<str:username>/',check_user,name = 'check_user'),
    path('check_bill/<int:id>/',check_bill,name = 'check_bill'),
    path('user_profile/<str:username>/',user_profile,name = 'user_profile'),
    path('user_bill/<int:id>/',user_bill,name = 'user_bill'),
    path('ajax/bills/',ajax_bills_emp,name  = 'ajax_bills_emp'),
    path('ajax/users/',ajax_users,name = 'ajax_users'),
    path('ajax/user/',ajax_user,name = 'ajax_user'),
    path('dash_board/<str:username>/',dash_board,name='dash_board'),
    path('ajax/normal_user/chart/',ajax_chart,name='ajax_chart'),

    ]

SAREV/smart_meter-master/sm_platform/profiles/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'profiles'

urlpatterns = [
    path('redirect/',redirect_profile,name = 'redirect_profile'),
    path('<str:username>/',profile_view,name = 'profile'),
    path('<str:username>/complete/',profile_complete,name = 'profile_complete'),
    ]

SAREV/smart_meter-master/sm_platform/sm_platform/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls' , namespace = 'accounts')),
    path('profiles/',include('profiles.urls' , namespace = 'profiles')),
    path('manager/',include('manager.urls', namespace = 'manager')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAREV/smart_meter-master/sm_platform/manager/models.py
from django.db import models
from accounts.models import *
# Create your models here.



class Data(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    voltage = models.FloatField()
    current = models.FloatField()
    power = models.FloatField()
    date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.user.username + "'s data"


class Bill(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    voltage = models.FloatField(null = True)
    avgCurrent = models.FloatField(null = True)
    power = models.FloatField()
    date = models.DateTimeField(auto_now_add = True)
    payed = models.BooleanField(default ='False')
    amount = models.FloatField()

    def save(self, *args, **kwargs):
        self.amount = self.power * 0.2
        super().save(*args, **kwargs)


    def __str__(self):
        return self.user.username + "'s Bill"

SAREV/smart_meter-master/sm_platform/manager/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from accounts.models import User , Profile
from .models import Data , Bill
from	django.utils.translation	import	gettext_lazy	as	_
from django.contrib import messages
from django.contrib.auth import authenticate
from .decorators import *
from django.core import serializers
import json
from django.http import JsonResponse

# Create your views here.

def add_data(request,distributerName,distributerPass,meterNumber,voltage,current):
    distributer = authenticate(username=distributerName, password=distributerPass)
    if distributer is not None:
        try:
            meter = Profile.objects.get(meterNumber = meterNumber)
            try:
                user = meter.user
                power = float(current) * float(voltage)
                data = Data.objects.create(user = user , voltage = voltage , current = current ,power = power)
                data.save()
            except Exception as err:
                return HttpResponse("ERR - "+str(err),content_type="text/plain")
        except Exception as err:
            return HttpResponse("ERR - "+str(err),content_type="text/plain")

        if (Data.objects.filter(user=user).count() % 6) == 0:
            avgCurrent = 0
            avgVoltage = 0
            for data in Data.objects.filter(user = user).order_by('-id')[:6]:
                power = power + data.power
                avgCurrent = avgCurrent + ( data.current / 6 )
                avgVoltage = avgVoltage + ( data.voltage / 6 )

            try:
                Bill.objects.create(user = user , avgCurrent = avgCurrent,voltage = avgVoltage , power = power)
                return HttpResponse("DONE - BILL CREATED" , content_type = "text/plain")
            except:
                return HttpResponse("ERR - unable to create a Bill",content_type="text/plain")
        return HttpResponse("DONE",content_type="text/plain")

    return HttpResponse("ERR - meter number is not defined",content_type="text/plain")


@login_required
@profile_complete
def get_bill(request,username,id):
    print(username,id)
    avgCurrent = 0
    if request.user.username == username:
        try:
            bill = Bill.objects.get(id=id)
            if bill:
                return render(request,'manager/bil.html',{'bill':bill})
            else:
                message = _("unable to find the bill with id of {}".format(id))
                messages.warning(request,message)
                return redirect("profiles:profile",request.user.username)

        except Exception as err:
            print(str(err))
            message = _("trouble with finding the bill with id of {}".format(id))
            messages.warning(request,message)

    return redirect("profiles:profile",request.user.username)


@login_required
@profile_complete
def dash_board(request,username):
    if request.user.username == username :
        try:
            bills = Bill.objects.filter(user = request.user).order_by('-id')
        except:
            bills = None
            data = None
        return render(request,"manager/dash_board.html",{'bills':bills})

    return redirect("profiles:profile",request.user.username)



@login_required
@profile_complete
def ajax_chart(request):
    if request.is_ajax():
        powerList = []
        dateList = []
        currentList = []
        datas = Data.objects.filter(user = request.user)
        if datas:
            for data in datas:
                powerList.append(data.power)
                dateList.append(data.date.date())
                currentList.append(data.current)

            return JsonResponse({'power':powerList,'current' : currentList,'date':dateList},safe=False,status = 200)

        return JsonResponse(None,safe=False,status = 400)



@login_required
@profile_complete
def ajax_bills(request):
    if request.is_ajax() :
        idList = []
        powerList = []
        currentList = []
        voltageList = []
        dateList = []
        currentList = []
        amountList = []
        datas = Bills.objects.filter(user = request.user)
        if(datas):
            for data in datas:
                idList.append(data.id)
                powerList.append(data.power)
                dateList.append(data.date.date())
                currentList.append(data.avgCurrent)
                voltageList.append(data.avgVoltage)
                amountList.append(data.amount)

            return JsonResponse({'id':idList,'power':powerList,'current' : currentList,'voltage' : voltageList,'amount': amountList,'date':dateList},safe=False,status = 200)

        return JsonResponse(None,safe=False,status = 400)


@login_required
@profile_complete
def ajax_bills_emp(request):
    if request.is_ajax() and (request.user.employee or request.user.is_admin):
        billsList = []
        billDict = {}
        try:
            bills = Bill.objects.filter(payed = False)
            for bill in bills:
                billDict['id'] = bill.id
                billDict['username'] = bill.user.username
                billDict['power'] = bill.power
                billDict['amount'] = bill.amount
                billDict['date'] = bill.date
                billDict['payed'] = bill.payed
                billsList.append(billDict.copy())
            return JsonResponse({'bills':billsList},safe=False,status = 200)
        except:
            return JsonResponse(None,safe=False,status = 200)
    return JsonResponse(None,safe=False,status = 400)


@login_required
@profile_complete
def ajax_user(request):
    if request.is_ajax() and (request.user.employee or request.user.is_admin):
        usersList = []
        userDict = {}
        phone = request.GET.get('phone', None)
        if phone:
            try:
                user = User.objects.get(phone = phone)
                userDict['username'] = user.username
                userDict['phone'] = user.phone
                userDict['email'] = user.email
                userDict['joined'] = user.joined
                usersList.append(userDict.copy())
                return JsonResponse({'users':usersList},safe=False,status = 200)
            except:
                return JsonResponse(None,safe=False,status = 200)
        return JsonResponse(None,safe=False,status = 200)

    return JsonResponse(None,safe=False,status = 400)

@login_required
@profile_complete
def ajax_users(request):
    if request.is_ajax() and (request.user.employee or request.user.is_admin):
        usersList = []
        userDict = {}
        try:
            profiles = Profile.objects.filter(profileComplete = False)
            for profile in profiles:
                userDict['id'] = profile.user.id
                userDict['username'] = profile.user.username
                userDict['phone'] = profile.user.phone
                userDict['email'] = profile.user.email
                userDict['joined'] = profile.user.joined
                userDict['profileComplete'] = profile.profileComplete
                usersList.append(userDict.copy())
            return JsonResponse({'users':usersList},safe=False,status = 200)
        except:
            return JsonResponse(None,safe=False,status = 200)
    return JsonResponse(None,safe=False,status = 400)


@login_required
@profile_complete
def check_user(request,username):
    if request.user.is_admin or request.user.employee:
        try:
            user = Profile.objects.get(user__username = username)
            if user:
                user.profileComplete = True
                user.save()
                message = _("Profile with username - {} - confirmed".format(username))
                messages.success(request,message)
                return redirect('manager:dash_board',request.user.username)
        except:
            message = _("Unable to confirm profile with username - {} -".format(username))
            messages.warning(request,message)
            return redirect('manager:dash_board',request.user.username)
    return redirect('profiles:profile',request.user.username)

@login_required
@profile_complete
def check_bill(request,id):
    if request.user.is_admin or request.user.employee:
        try:
            bill = Bill.objects.get(id = id)
            if bill:
                bill.payed = True
                bill.save()
                message = _("Bill with id number - {} - marked as payed".format(id))
                messages.success(request,message)
                return redirect('manager:dash_board',request.user.username)
        except:
            message = _("Unable to mark the Bill with id number - {} - as payed".format(id))
            messages.warning(request,message)
            return redirect('manager:dash_board',request.user.username)
    return redirect('profiles:profile',request.user.username)


@login_required
@profile_complete
def user_bill(request,id):
    if request.user.is_admin or request.user.employee:
        try:
            bill = Bill.objects.get(id = id)
            if bill:
                if bill.payed:
                    message = _("Bill with id number - {} - is already payed".format(id))
                    messages.warning(request,message)
                    return redirect('manager:dash_board',request.user.username)
                return render(request,'manager/user_bill.html',{'bill':bill})
            else:
                message = _("Unable to get the Bill with id number - {} -".format(id))
                messages.warning(request,message)
                return redirect('manager:dash_board',request.user.username)
        except:
            message = _("Unable to get the Bill with id number - {} -".format(id))
            messages.warning(request,message)
            return redirect('manager:dash_board',request.user.username)

    return redirect('profiles:profile',request.user.username)

@login_required
@profile_complete
def user_profile(request,username):

SAREV/smart_meter-master/sm_platform/manager/templates/manager/dash_board.html
{%	extends	"base.html"	%}
{% load i18n %}
{% load static %}
{% block title %}<title>
  {% trans "dash board" %}
</title>
{% endblock title %}
{% block css %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" />
<!-- Favicons -->

<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

<link rel="stylesheet" type="text/css" href='{% static "manager/dash_board.css" %}'>
{% endblock css %}
{% block js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'manager/dash_board.js' %}"></script>

{% endblock js %}

{% block content %}

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
<a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">    <img  class="text-right align-top" id="hat" src="{% static 'accounts/Logo_sonelgaz.png' %}" alt="" width="30" height="30" >

</a>
<button id="searchButt" class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<input id="search" data-pageType="" class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
<div class="navbar-nav">
  <div class="nav-item text-nowrap">
    <a class="nav-link px-3" href="{% url 'accounts:logout' %}">{% trans "Logout" %}<span data-feather="log-out"></span></i></a>
  </div>
</div>
</header>

<div class="container-fluid">
<div class="row">
  <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>{% trans "profile settings" %}</span>
          <span data-feather="settings"></span>
      </h6>
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profiles:profile' user.username %}">
            <span data-feather="user"></span>
            {% trans "Profile" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:password_change' user.username %}">
            <span data-feather="eye"></span>
            {% trans "Change Password" %}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:delete_account' user.username %}">
            <span data-feather="alert-triangle"></span>
            {% trans "Delete Account" %}
          </a>
        </li>
      </ul>

      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>{% trans "Usage" %}</span>
          <span data-feather="zap"></span>
      </h6>
      <ul class="nav flex-column mb-2">
        {% if user.employee or user.is_admin %}
        <li id="getBillsEmp" class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="credit-card"></span>
            {% trans "Bills" %}
          </a>
        </li>
        <li id="getUsersEmp" class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="users"></span>
            {% trans "New Users" %}
          </a>
        </li>
        {% else %}
        <li id="getBills" class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="credit-card"></span>
            {% trans "Bills" %}
          </a>
        </li>
        <li id="getChart" class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="activity"></span>
            {% trans "Consumption Chart" %}
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main id="main" class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  {% include "accounts/messages.html" %}
  {% if user.employee or user.is_admin %}
  <div id="usersEmp" class="table-responsive">
    <h2>{% trans "New Users" %}</h2>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">{% trans "username" %}</th>
          <th scope="col">{% trans "email" %}</th>
          <th scope="col">{% trans "phone" %}</th>
          <th scope="col">{% trans "date" %}</th>
          <th scope="col">{% trans "status" %}</th>
        </tr>
      </thead>
      <tbody id="usersEmpTab">
      </tbody>
    </table>
  </div>

  <div id="billsEmp" class="table-responsive">
    <h2>{% trans "Unpayed Bills" %}</h2>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">{% trans "username" %}</th>
          <th scope="col">{% trans "power" %}</th>
          <th scope="col">{% trans "amount" %}</th>
          <th scope="col">{% trans "date" %}</th>
          <th scope="col">{% trans "status" %}</th>
        </tr>
      </thead>
      <tbody id="billsEmpTab">
      </tbody>
    </table>
  </div>

  {% else %}

  <div id="alert" class="alert alert-danger" role="alert">
    {% trans "No data Found" %}
  </div>
    <div id="chart">
      <h2>{% trans "Power Consumption Chart" %}</h2>
      <canvas  class="my-4 w-100" id="myChart" width="900" height="380"></canvas>
      <h2>{% trans "Current Consumption Chart" %}</h2>
      <canvas  class="my-4 w-100" id="myChart2" width="900" height="380"></canvas>
    </div>

    <div id="table" class="table-responsive">
      <h2>{% trans "Bills" %}</h2>
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">{% trans "Date" %}</th>
            <th scope="col">{% trans "Voltage(V)" %}</th>
            <th scope="col">{% trans "Average Current(A)" %}</th>
            <th scope="col">{% trans "Power(W)" %}</th>
            <th scope="col">{% trans "Status" %}</th>
          </tr>
        </thead>
        <tbody>
          {% if bills %}
            {% for bill in bills %}
            <tr>
              <td><a href="{% url 'manager:get_bill' user.username bill.id %}">{{bill.id}}</a></td>
              <td>{{bill.date}}</td>
              <td>{{bill.voltage|floatformat:3}}</td>
              <td>{{bill.avgCurrent|floatformat:3}}</td>
              <td>{{bill.power|floatformat:3}}</td>
            </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>
    {% endif %}


  </main>
</div>
</div>


{% endblock content %}

SAREV/smart_meter-master/sm_platform/manager/templates/manager/user_profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}<title>
  {{user.username}}
</title>
{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'profiles/profile.css' %}">
{% endblock css %}
{% block js %}
<script type="text/javascript" src="{% static 'profiles/profile.js' %}"></script>
{% endblock js %}
{% block content %}


<div class="container">
        <div class="row">

            <div class="col-12">
                <div class="card">
                          {% include "accounts/messages.html" %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3">
                                <div class="image-container">
                                    <img src="{{user.profile.profileImage.url }}" id="imgProfile" style="width: 250px; height: 300px" class="img-thumbnail" />
                                </div>
                              </div>
                                <div class="col ml-3" style="margin-top: 0.5em;">
                                    <h2 class="d-block" style=" font-size: 2.8em ;font-weight: bold; ">{{user.username}}</h2>
                                    <h6 class="d-block" style="font-weight:bold; margin-top: 1em;">{{user.email}}</h6>
                                    <h6 class="d-block" style="font-weight:bold; margin-top: 1em;">{{user.phone}}</h6>
                                    <a href='{% url "manager:check_user" user.username %}' ><button type="button" class="btn btn-outline-primary" style="margin-top: 3em;">{% trans "Check Profile" %}</button></a>
                                </div>

                                  <div class="col" >
                                    <img  class="text-right align-top" id="hat" src="{% static 'accounts/Logo_sonelgaz.png' %}" alt="" width="100" height="120" >
                                  </div>

                            </div>

                        </div>

                        <div class="row">
                            <div class="col-12" style="margin: 1.5em;">
                                <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="basicInfo-tab" data-toggle="tab" href="#basicInfo" role="tab" aria-controls="basicInfo" aria-selected="true">{% trans "Info" %}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link"  href = '{% url "manager:dash_board" this_user.username %}' role="tab" >{% trans "Dashboard" %}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link"   href='{% url "accounts:logout" %}' role="tab" >{% trans "Logout" %}</a>
                                    </li>
                                </ul>
                                <div class="tab-content ml-1" id="myTabContent">
                                    <div class="tab-pane fade show active" id="basicInfo" role="tabpanel" aria-labelledby="basicInfo-tab">


                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "First Name" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.firstName}}
                                            </div>
                                        </div>
                                        <hr />

                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Last Name" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.lastName}}
                                            </div>
                                        </div>
                                        <hr />


                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Birth Date" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.birthday }}
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Address" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                               {{user.profile.address}}
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Gender" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.gender}}
                                            </div>
                                        </div>
                                        <hr />

                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Joined" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.joined}}
                                            </div>
                                        </div>

                                    </div>
                                    <div class="tab-pane fade" id="connectedServices" role="tabpanel" aria-labelledby="ConnectedServices-tab">
                                        Facebook, Google, Twitter Account that are connected to this account
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>

                </div>
            </div>
        </div>
    </div>

        {% endblock content %}