SAREV/smart_meter-master/sm_platform/accounts/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    #path('register/activate/<uidb64>/<token>/',user_activation_view , name = 'activate'),
    path('register/',RegisterView.as_view(),name = 'register'),
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/registration/login.html' , redirect_authenticated_user = True),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'accounts/registration/logged_out.html'),name = 'logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(
                                            template_name ='accounts/registration/password_reset.html',
                                            email_template_name = 'accounts/registration/password_reset_email.html',
                                            success_url='done/'),
                            name='password_reset'),

    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(
                                            template_name ='accounts/registration/password_reset_done.html'),
                            name='password_reset_done'),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
                                            template_name ='accounts/registration/password_reset_confirm.html',
                                            success_url ='/accounts/reset/done/'),
                            name='password_reset_confirm'),

    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(
                                            template_name ='accounts/registration/password_reset_complete.html'),
                            name='password_reset_complete'),

    path('<str:username>/password_change/',
            auth_views.PasswordChangeView.as_view(template_name = "accounts/changePassword.html",
                success_url ='done/'),
                                name='password_change'),

    path('<str:username>/password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/changePasswordDone.html") ,
                                                name='password_change_done'),
    path('<str:username>/delete_account/confirm/',delete_account_confirm, name = 'delete_account_confirm' ),
    path('<str:username>/delete_account/',delete_account , name = 'delete_account'),


]

SAREV/smart_meter-master/sm_platform/manager/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'manager'

urlpatterns = [
    path('add_data/<distributerName>/<distributerPass>/<meterNumber>/<voltage>/<current>/',add_data,name ='add_data'),
    path('get_bill/<str:username>/<id>/',get_bill,name='get_bill'),
    path('check_user/<str:username>/',check_user,name = 'check_user'),
    path('check_bill/<int:id>/',check_bill,name = 'check_bill'),
    path('user_profile/<str:username>/',user_profile,name = 'user_profile'),
    path('user_bill/<int:id>/',user_bill,name = 'user_bill'),
    path('ajax/bills/',ajax_bills_emp,name  = 'ajax_bills_emp'),
    path('ajax/users/',ajax_users,name = 'ajax_users'),
    path('ajax/user/',ajax_user,name = 'ajax_user'),
    path('dash_board/<str:username>/',dash_board,name='dash_board'),
    path('ajax/normal_user/chart/',ajax_chart,name='ajax_chart'),

    ]

SAREV/smart_meter-master/sm_platform/profiles/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'profiles'

urlpatterns = [
    path('redirect/',redirect_profile,name = 'redirect_profile'),
    path('<str:username>/',profile_view,name = 'profile'),
    path('<str:username>/complete/',profile_complete,name = 'profile_complete'),
    ]

SAREV/smart_meter-master/sm_platform/sm_platform/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls' , namespace = 'accounts')),
    path('profiles/',include('profiles.urls' , namespace = 'profiles')),
    path('manager/',include('manager.urls', namespace = 'manager')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAREV/smart_meter-master/sm_platform/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from	django.utils.translation	import	gettext_lazy	as	_
from .validators import fake_email_validation , phone_number_validation
from django.template.defaultfilters import slugify


class User(AbstractUser):
    email = models.EmailField(max_length = 255,unique = True , validators = [fake_email_validation,] )
    username = models.CharField(max_length = 20,unique = True )
    phone = models.CharField(max_length = 10 ,unique = True ,default = "xxxxxxxxx" ,validators = [phone_number_validation,])
    joined = models.DateTimeField(auto_now_add = True)
    is_admin = models.BooleanField(default = False)
    employee = models.BooleanField(default = False)

    USERNAME_FIELD  = 'email'
    REQUIRED_FIELDS = ['username','phone']

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        if self.phone[0] == '0':
            self.phone = self.phone[1:] # self.value is a model field.
        self.email = self.email.lower()
        super().save(*args, **kwargs)

GENDER = (
    ('MALE',_('MALE')),
    ('FEMALE',_('FEMALE')),
)

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE,unique = True)
    firstName = models.CharField( _('first name'),max_length = 20 , null = True)
    lastName = models.CharField(_('last name'),max_length = 20, null = True)
    meterNumber = models.CharField(max_length = 10 ,unique = True ,validators = [phone_number_validation,])
    gender = models.CharField(_('gender') , choices = GENDER ,max_length = 10, null = True )
    profileImage = models.ImageField(_('profile image'),upload_to = 'usersImages')
    birthday = models.DateField(_('birthday'), null = True )
    address = models.CharField(_('addess'),max_length = 100, null = True )
    profileComplete = models.BooleanField(default ='False')

    def save(self, *args, **kwargs):
        self.meterNumber = self.user.phone
        super().save(*args,**kwargs)

    def __str__(self):  # string representation of the profile when it gets created.
        return slugify(self.user.username + ' Profile')

SAREV/smart_meter-master/sm_platform/accounts/forms.py
# accounts.forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.template.defaultfilters import slugify
from django.utils import timezone
from .models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as	_


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label=_('password'))
    password2 = forms.CharField(label=_('Confirm password'))

    class Meta:
        model = User
        fields = ('email','username','phone')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError(_("email is taken"))
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone[0] == '0':
            phone = phone[1:]
        qs = User.objects.filter(phone = phone)
        if qs.exists():
            raise forms.ValidationError(_("phone number already in use"))
        return phone

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username = username)
        if qs.exists():
            raise forms.ValidationError(_("username exists"))
        return username

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        condition1 = ( password1 and password2 )
        condition2 = ( password1 == password2 )
        condition3 = ( len(password2) > 8 )
        if not ( condition1 and condition2 ):
            raise forms.ValidationError(_("Passwords don't match"))
        if not condition3:
            raise forms.ValidationError(_("Password length less than 8"))

        return password2

SAREV/smart_meter-master/sm_platform/accounts/views.py
from django.shortcuts import render , redirect
from django.template.loader import render_to_string
from django.views.generic import View
from .models import User,Profile
from .forms import *  # RegisterForm
from django.utils.encoding import force_bytes, force_text
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .token_generator import account_activation_token
from django.core.mail import EmailMessage
from	django.utils.translation	import	gettext_lazy	as	_
import requests
from django.conf import settings
from .decorators import check_recaptcha
from django.contrib import messages
from django.http import JsonResponse

# Create your views here.

class	RegisterView(View):
    def post(self,request):
        form = RegisterForm(request.POST)
        agree = request.POST.get('agree-term')

        if	form.is_valid()  and agree:
            # rechaptcha validation
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            # End reCAPTCHA validation

            if result['success']:
                #	Create	a	new	user	object	but	avoid	saving	it	yet
                new_user = form.save(commit=False)
                #	Set	the	chosen	password
                new_user.set_password(form.cleaned_data['password1'])
                #new_profile = profileForm.save()
                #new_user.profile = new_profile
                #	Save	the	User	object
                new_user.is_active = True
                new_user.save()
                message = _("Your account was created successfully , you can login now.")
                messages.success(request,message)
                return redirect("accounts:login")
            else:
                agreeErrorText = _("you must agree to all statements in Terms of service")
                recaptchaErrorText = _("Invalid reCAPTCHA. Please try again.")
                return render(request,'accounts/register.html',{'form':form,'recaptcha':recaptchaErrorText})

        else:
            agreeErrorText = _("you must agree to all statements in Terms of service")
            recaptchaErrorText = _("Invalid reCAPTCHA. Please try again.")
            return render(request,'accounts/register.html',{'form':form,'agreeError':agreeErrorText,'recaptcha':recaptchaErrorText})

    def get(self,request):
        if request.user.is_authenticated:
            return	redirect('profiles:profile',request.user.username)

        form = RegisterForm()
        return render(request,'accounts/register.html',{'form':form})


@login_required
def delete_account(request,username):
    if request.user.username == username:
        return render(request,'accounts/delete_account.html')


@login_required
def delete_account_confirm(request,username):
    if request.user.username == username:
        try:
            User.objects.get(username = username).delete()
            message = _("the Account was deleted successfully.")
            messages.success(request,message)
        except:
            message = _("Unable to delete your Account.")
            messages.warning(request,message)

        return redirect('accounts:login')

    return redirect('profiles:profile',request.user.username)

SAREV/smart_meter-master/sm_platform/accounts/templates/accounts/404_error.html
page not found

SAREV/smart_meter-master/sm_platform/accounts/templates/accounts/changePassword.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/login.css' %}">
{% endblock css %}
{%	block	title	%}
<title>
	{% trans "Change	your	password" %}
</title>
{%	endblock	%}
{%	block	content	%}

    <div class="container">
			<div class="text-center mb-4">
		    <img class="mb-4" src="{% static 'accounts/Logo_sonelgaz.png' %}" alt="" width="72" height="72">
		  </div>
    <form		action="." method="post" class="form-signin">{% csrf_token %}
			<div class="form-label-group">
				<input type="password" id="inputPassword" class="form-control" placeholder='{% trans "old password" %}' name="old_password" required>
				<label for="inputPassword">{% trans "old password" %}</label>
			</div>
        {% if form.errors and form.old_password.errors %}
          <div class="alert alert-danger" role="alert">
                {% for error in form.old_password.errors %}
                {{error}}
                  {% endfor %}
						</div>
          {% endif %}
					<div class="form-label-group">
						<input type="password" id="inputPassword1" class="form-control" placeholder='{% trans "new password" %}' name="new_password1" required>
						<label for="inputPassword1">{% trans "new password" %}</label>
					</div>
				{% if form.errors and form.new_password1.errors %}
					<div class="alert alert-danger" role="alert">
								{% for error in form.new_password1.errors %}
								{{error}}<br>
									{% endfor %}
							</div>
					{% endif %}
					<div class="form-label-group">
						<input type="password" id="inputPassword2" class="form-control" placeholder='{% trans "confirm password" %}' name="new_password2" required>
						<label for="inputPassword2">{% trans "confirm password" %}</label>
					</div>
            {% if form.errors and form.new_password2.errors %}
              <div class="alert alert-danger" role="alert">
                    {% for error in form.new_password2.errors %}
                    {{error}}<br>
                      {% endfor %}
									</div>
              {% endif %}

      <button class="btn btn-lg btn-outline-warning btn-block" type="submit" value='{% trans "Change" %}' style="margin-top : 2em ;">{% trans "Change" %}</button>
    </form>

  </div>



{%	endblock	%}

SAREV/smart_meter-master/sm_platform/accounts/templates/accounts/changePasswordDone.html
{%	extends	"base.html"	%}
{% load i18n %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/login.css' %}">
{% endblock css %}
{%	block	title	%}
<title>
	{% trans "Password Changed" %}
</title>{%	endblock	%}
{%	block	content	%}
<div class="container">
  <div class="text-center mb-4">
    <img class="mb-4" src="{% static 'accounts/Logo_sonelgaz.png' %}" alt="" width="72" height="72">
  </div>
<div class="alert alert-success alertMessage" role="alert">
  <h4 class="alert-heading">{% trans "Password	changed successfully" %}</h4>
  <p>{% trans "Your	password	has	been	changed successfully." %}</p>
  <hr>
  <a	 href="{% url 'profiles:profile' user.username %}" class="alert-link">{% trans "back to profile" %} </a>
</div>
</div>
{%	endblock	%}

SAREV/smart_meter-master/sm_platform/accounts/templates/accounts/delete_account.html
{%	extends	"base.html"	%}
{% load i18n %}
{% load static %}
{%	block	title	%}<title>
	{% trans "Delete Account" %}
</title>
{%	endblock title	%}
{%	block	content	%}
<div class="container">
	<div class="text-center mb-4">
    <img class="mb-4" src="{% static 'accounts/Logo_sonelgaz.png' %}" alt="" width="72" height="72">
  </div>
	<div class="alert alert-warning alertMessage" role="alert">
	  <h4 class="alert-heading">{% trans "Delete Account" %}</h4>
		<p> {% trans "Confirm deletion by clicking on Confirm ." %}</p><hr>
			<a	href="{%	url 'accounts:delete_account_confirm'	user.username %}" class="alert-link">{% trans "Confirm" %}</a>
</div>
</div>
{%	endblock	%}

SAREV/smart_meter-master/sm_platform/accounts/templates/accounts/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

SAREV/smart_meter-master/sm_platform/accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}<title>
  {% trans "Register" %}
</title>
{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/login.css' %}">
{% endblock css %}

  {% block content %}

    <div class="container">
          {% include "accounts/messages.html" %}

          <form method="POST" class="form-signin">{% csrf_token %}
              <div class="text-center mb-4">
                <img class="mb-4" src="{% static 'accounts/Logo_sonelgaz.png' %}" alt="" width="72" height="72">
              </div>
                <div class="form-label-group">
                  <input type="text"  id="inputUserName" class="form-control" placeholder='{% trans "username" %}' name="username" required autofocus>
                  <label for="inputUserName">{% trans "username" %}</label>
                </div>
                {% if form.errors and form.username.errors %}
                    <div class="alert alert-danger" role="alert">
                    {% for error in form.username.errors %}
                      {{error}}
                    {% endfor %}<br>
                  </div>
                {% endif %}

                <div class="form-label-group">
                  <input type="email" id="inputEmail" class="form-control form-control-sm" placeholder='{% trans "Email" %}' name="email" required autofocus>
                  <label for="inputEmail">{% trans "Email" %}</label>
                </div>
                {% if form.errors and form.email.errors%}
                  <div class="alert alert-danger" role="alert">
                        {% for error in form.email.errors %}
                        {{error}}<br>
                  </div>
                          {% endfor %}
                  {% endif %}
                  <div class="form-label-group">
                    <input type="number" id="inputPhone" class="form-control form-control-sm" placeholder='{% trans "phone number" %}' name="phone" required autofocus>
                    <label for="inputPhone">{% trans "phone number" %}</label>
                  </div>
                  {% if form.errors and form.phone.errors%}
                <div class="alert alert-danger" role="alert">
                        {% for error in form.phone.errors %}
                        {{error}}<br>
                  </div>
                          {% endfor %}
                  {% endif %}
                  <div class="form-label-group">
                    <input type="password" id="inputPassword1" class="form-control form-control-sm" placeholder='{% trans "password" %}' name="password1" required>
                    <label for="inputPassword1">{% trans "password" %}</label>
                  </div>

                  <div class="form-label-group">
                    <input type="password" id="inputPassword2" class="form-control form-control-sm" placeholder='{% trans "confirm password" %}' name="password2" required>
                    <label for="inputPassword2">{% trans "confirm password" %}</label>
                  </div>
                  {% if form.errors and form.password2.errors%}
                    <div class="alert alert-danger" role="alert">
                          {% for error in form.password2.errors %}
                          {{error}}<br>
                    </div>
                            {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                        <label for="agree-term" class="label-agree-term"><span><span></span></span>
                        <a href="#" class="term-service">  {% trans "I agree all statements in  Terms of service" %}</a></label>
                    </div>
                    {% if agreeError %}
                    <div class="alert alert-danger" role="alert">
                          {{agreeError}}<br>
                    </div>
                    {% endif %}
                    <script src='https://www.google.com/recaptcha/api.js'></script>
                      <div class="g-recaptcha" data-sitekey="6Le9I8MaAAAAAJLCvEuD_d_s2piLnJbs9EQU5nd2"></div>
                      {% if recaptcha %}
                    <div class="alert alert-danger" role="alert">
                        {{recaptcha}}<br>
                      </div>
                      {% endif %}
                            <button class="btn  btn-outline-warning btn-block" type="submit" value='{% trans "Register" %}' style="margin-top : 2em ; margin-bottom: 1em; ">{% trans "Sign up" %}</button>
                                <hr>
                                <a  href = "{% url "accounts:login" %}" value='{% trans "Login" %}'>{% trans "already have an account" %}</a>

                        </form>

                    </div>



{% endblock content %}

SAREV/smart_meter-master/sm_platform/accounts/templates/accounts/register_done.html
{%	extends	"base.html"	%}
{% load i18n %}
{%	block	title	%}{% trans "Welcome" %}{%	endblock	%}
{%	block	content	%}

<div class="container">
  <div class="alert alert-success" role="alert">
    <h4 class="alert-heading">{% blocktrans %} Welcome	{{ new_user.username	}} {% endblocktrans %}</h4>
    <p>{% trans "Your	account	has	been	successfully	created" ,we sent you an email message with a confirmation link <br>
          , Please check your emai and follow the link ,to make activate your PayDz account ." %}</p>
    <hr>
    <a	href="{%	url 'accounts:login'	%}" class="alert-link">{% trans  "log-in Now" %}	</a>
  </div>
  </div>
{%	endblock	%}