SAREV/smart_meter-master/sm_platform/accounts/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    #path('register/activate/<uidb64>/<token>/',user_activation_view , name = 'activate'),
    path('register/',RegisterView.as_view(),name = 'register'),
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/registration/login.html' , redirect_authenticated_user = True),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'accounts/registration/logged_out.html'),name = 'logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(
                                            template_name ='accounts/registration/password_reset.html',
                                            email_template_name = 'accounts/registration/password_reset_email.html',
                                            success_url='done/'),
                            name='password_reset'),

    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(
                                            template_name ='accounts/registration/password_reset_done.html'),
                            name='password_reset_done'),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
                                            template_name ='accounts/registration/password_reset_confirm.html',
                                            success_url ='/accounts/reset/done/'),
                            name='password_reset_confirm'),

    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(
                                            template_name ='accounts/registration/password_reset_complete.html'),
                            name='password_reset_complete'),

    path('<str:username>/password_change/',
            auth_views.PasswordChangeView.as_view(template_name = "accounts/changePassword.html",
                success_url ='done/'),
                                name='password_change'),

    path('<str:username>/password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/changePasswordDone.html") ,
                                                name='password_change_done'),
    path('<str:username>/delete_account/confirm/',delete_account_confirm, name = 'delete_account_confirm' ),
    path('<str:username>/delete_account/',delete_account , name = 'delete_account'),


]

SAREV/smart_meter-master/sm_platform/manager/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'manager'

urlpatterns = [
    path('add_data/<distributerName>/<distributerPass>/<meterNumber>/<voltage>/<current>/',add_data,name ='add_data'),
    path('get_bill/<str:username>/<id>/',get_bill,name='get_bill'),
    path('check_user/<str:username>/',check_user,name = 'check_user'),
    path('check_bill/<int:id>/',check_bill,name = 'check_bill'),
    path('user_profile/<str:username>/',user_profile,name = 'user_profile'),
    path('user_bill/<int:id>/',user_bill,name = 'user_bill'),
    path('ajax/bills/',ajax_bills_emp,name  = 'ajax_bills_emp'),
    path('ajax/users/',ajax_users,name = 'ajax_users'),
    path('ajax/user/',ajax_user,name = 'ajax_user'),
    path('dash_board/<str:username>/',dash_board,name='dash_board'),
    path('ajax/normal_user/chart/',ajax_chart,name='ajax_chart'),

    ]

SAREV/smart_meter-master/sm_platform/profiles/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'profiles'

urlpatterns = [
    path('redirect/',redirect_profile,name = 'redirect_profile'),
    path('<str:username>/',profile_view,name = 'profile'),
    path('<str:username>/complete/',profile_complete,name = 'profile_complete'),
    ]

SAREV/smart_meter-master/sm_platform/sm_platform/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls' , namespace = 'accounts')),
    path('profiles/',include('profiles.urls' , namespace = 'profiles')),
    path('manager/',include('manager.urls', namespace = 'manager')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAREV/smart_meter-master/sm_platform/profiles/models.py
from django.db import models

# Create your models here.

SAREV/smart_meter-master/sm_platform/profiles/forms.py
from django import forms
from accounts.models import *
from	django.utils.translation	import	gettext_lazy	as	_
from django import forms
from accounts.validators import *

class profileEditForm(forms.ModelForm):     # form for creating / editing  a profile
    class Meta:
        model = Profile
        fields = ('firstName','lastName','gender','birthday','address','profileImage')


class userEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','phone','email')


class addDataForm(forms.Form):
    meterNumber = models.CharField(max_length = 10 ,validators = [phone_number_validation,])
    voltage = models.FloatField()
    current = models.FloatField()

SAREV/smart_meter-master/sm_platform/profiles/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .decorators import *
from accounts.models import *
from .forms import *
from	django.utils.translation	import	gettext_lazy	as	_
from django.contrib import messages
from django.contrib.auth import authenticate


@login_required
@profile_complete
def profile_view(request,username):
    if request.user.username == username:
        user = User.objects.get(username = username)
        return render(request,'profiles/profile.html')
    else:
       return redirect("profiles:profile_complete",request.user.username)

@login_required
@profile_complete_reverse
def profile_complete(request,username):
    if request.method == "POST" and request.user.username == username :
        user = request.user
        profile = Profile.objects.get(user = user)

        profileForm = profileEditForm(request.POST,request.FILES ,instance = profile )
        print(profileForm)
        profileForm.meterNumber = user.phone
        print(profileForm)
        if profileForm.is_valid():
            profileForm.save()
            message = _("Your profile info was setted successfully.")
            messages.success(request,message)
            return redirect("profiles:profile",user)
        else:
            return render(request,"profiles/profile_complete.html",{"profileEditForm" : profileForm ,})
    else:
        profileForm = profileEditForm()
        return render(request,"profiles/profile_complete.html",{"profileEditForm" : profileForm ,})


@login_required
def redirect_profile(request):
    return redirect('profiles:profile',request.user.username)

SAREV/smart_meter-master/sm_platform/profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}<title>
  {{user.username}}
</title>
{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'profiles/profile.css' %}">
{% endblock css %}
{% block js %}
<script type="text/javascript" src="{% static 'profiles/profile.js' %}"></script>
{% endblock js %}
{% block content %}


<div class="container">
        <div class="row">

            <div class="col-12">
                <div class="card">
                          {% include "accounts/messages.html" %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3">
                                <div class="image-container">
                                    <img src="{{user.profile.profileImage.url }}" id="imgProfile" style="width: 250px; height: 300px" class="img-thumbnail" />
                                </div>
                              </div>
                                <div class="col ml-3" style="margin-top: 0.5em;">
                                    <h2 class="d-block" style=" font-size: 2.8em ;font-weight: bold; ">{{user.username}}</h2>
                                    <h6 class="d-block" style="font-weight:bold; margin-top: 1em;">{{user.email}}</h6>
                                    <h6 class="d-block" style="font-weight:bold; margin-top: 1em;">{{user.phone}}</h6>
                                    <a href='{% url "accounts:password_change" user.username %}' ><button type="button" class="btn btn-outline-primary" style="margin-top: 3em;">{% trans "Edit Password" %}</button></a>
                                </div>

                                  <div class="col" >
                                    <img  class="text-right align-top" id="hat" src="{% static 'accounts/Logo_sonelgaz.png' %}" alt="" width="100" height="120" >
                                  </div>

                            </div>

                        </div>

                        <div class="row">
                            <div class="col-12" style="margin: 1.5em;">
                                <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="basicInfo-tab" data-toggle="tab" href="#basicInfo" role="tab" aria-controls="basicInfo" aria-selected="true">{% trans "Info" %}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link"  href = '{% url "manager:dash_board" user.username %}' role="tab" >{% trans "Dashboard" %}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link"   href='{% url "accounts:logout" %}' role="tab" >{% trans "Logout" %}</a>
                                    </li>
                                </ul>
                                <div class="tab-content ml-1" id="myTabContent">
                                    <div class="tab-pane fade show active" id="basicInfo" role="tabpanel" aria-labelledby="basicInfo-tab">


                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "First Name" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.firstName}}
                                            </div>
                                        </div>
                                        <hr />

                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Last Name" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.lastName}}
                                            </div>
                                        </div>
                                        <hr />


                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Birth Date" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.birthday }}
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Address" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                               {{user.profile.address}}
                                            </div>
                                        </div>
                                        <hr />
                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Gender" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.profile.gender}}
                                            </div>
                                        </div>
                                        <hr />

                                        <div class="row">
                                            <div class="col-sm-3 col-md-2 col-5">
                                                <label style="font-weight:bold;">{% trans "Joined" %}</label>
                                            </div>
                                            <div class="col-md-8 col-6">
                                                {{user.joined}}
                                            </div>
                                        </div>

                                    </div>
                                    <div class="tab-pane fade" id="connectedServices" role="tabpanel" aria-labelledby="ConnectedServices-tab">
                                        Facebook, Google, Twitter Account that are connected to this account
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>

                </div>
            </div>
        </div>
    </div>

        {% endblock content %}

SAREV/smart_meter-master/sm_platform/profiles/templates/profiles/profile_complete.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}<title>
  {% trans "Complete profile" %}
</title>
{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'profiles/profile_complete.css' %}">
{% endblock css %}
{% block js %}
<script type="text/javascript" src="{% static 'profiles/profile_complete.js' %}">

</script>
{% endblock js %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
<div class="row flex-lg-nowrap">

  <div class="col">
    <div class="row">
      <div class="col mb-3">
        <div class="card">
          <div class="card-body">
            <div class="e-profile">
              <div class="row">
                <div class="col-12 col-sm-auto mb-3">
                  <div class="mx-auto" style="width: 140px;">
                    <div class="d-flex justify-content-center align-items-center rounded"  style="height: 140px; background-color: rgb(233, 236, 239);">
                       <img src="http://placehold.it/150x150" id="imgProfile" style="width: 150px; height: 150px" class="img-thumbnail" />
                    </div>
                  </div>
                </div>
                <div class="col d-flex flex-column flex-sm-row justify-content-between mb-3">
                  <div class="text-center text-sm-left mb-2 mb-sm-0">
                    <h4 class="pt-sm-2 pb-1 mb-0 text-nowrap">{{user.username}}</h4>
                    <p class="mb-0">{{user.email}}</p>
                    <div class="text-muted"><small>{{user.phone}}</small></div>

                  </div>
                  <div class="text-center text-sm-right">
                    <span class="badge badge-secondary">{% if user.is_admin %}{% trans "Administrator" %}
                      {% else %}
                      {% trans "Regular user" %}
                      {% endif %}
                    </span>
                    <div class="text-muted"><small>{% trans "Joined " %} {{user.joined}} </small></div>
                  </div>
                </div>

              </div>
              {% if profileEditForm.errors and profileEditForm.profileImage.errors %}
                  <div class="alert alert-danger" role="alert">
                  {% for error in profileEditForm.profileImage.errors %} ( Image field )
                    {{error}}
                  {% endfor %}<br>
                </div>
              {% endif %}
              <ul class="nav nav-tabs">
                <li class="nav-item"><a href="" class="active nav-link">{% trans "Information" %}</a></li>
              </ul>
              <div class="tab-content pt-3">
                <div class="tab-pane active">
                  <form class="form" method="POST" enctype="multipart/form-data">{% csrf_token %}

                    <div class="mt-2">
                      <input type="button" class="btn btn-primary" type="button" id="btnChangePicture" value='{% trans "Change picture" %}' style="margin:1.4em;" />
                      <input type="file" style="display: none;" id="profilePicture" name="profileImage" />
                    </div>
                    <div class="row">
                      <div class="col">
                        <div class="row">
                          <div class="col">
                            <div class="form-group">
                              <label>{% trans "First Name" %}</label>
                              <input class="form-control" type="text" name="firstName" placeholder="{% trans 'firstName' %}" required>
                            </div>
                            {% if profileEditForm.errors and profileEditForm.firstName.errors %}
                                <div class="alert alert-danger" role="alert">
                                {% for error in profileEditForm.firstName.errors %}
                                  {{error}}
                                {% endfor %}<br>
                              </div>
                            {% endif %}

                          </div>
                          <div class="col">
                            <div class="form-group">
                              <label>{% trans "Last Name" %}</label>
                              <input class="form-control" type="text" name="lastName" placeholder="{% trans 'lastName' %}" required>
                            </div>
                            {% if profileEditForm.errors and profileEditForm.lastName.errors %}
                                <div class="alert alert-danger" role="alert">
                                {% for error in profileEditForm.lastName.errors %}
                                  {{error}}
                                {% endfor %}<br>
                              </div>
                            {% endif %}
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                            <div class="form-group">
                              <label>{% trans "Gender" %}</label>
                              <select name="gender" class="form-control">
                                <option value="MALE">{% trans "Male" %}</option>
                                <option value="FEMALE">{% trans "Female" %}</option>

                              </select>
                            </div>
                            {% if profileEditForm.errors and profileEditForm.gender.errors %}
                                <div class="alert alert-danger" role="alert">
                                {% for error in profileEditForm.gender.errors %}
                                  {{error}}
                                {% endfor %}<br>
                              </div>
                            {% endif %}
                          </div>

                          <div class="col">
                            <div class="form-group">
                              <label>{% trans "Address" %}</label>
                              <input name="address" class="form-control" type="text" placeholder="wilaya , address" required>
                            </div>
                            {% if profileEditForm.errors and profileEditForm.address.errors %}
                                <div class="alert alert-danger" role="alert">
                                {% for error in profileEditForm.address.errors %}
                                  {{error}}
                                {% endfor %}<br>
                              </div>
                            {% endif %}
                          </div>
                        </div>
                        <div class="row">
                          <div class="col mb-3">
                            <div class="form-group">
                              <label>{% trans "Birthdate" %}</label>
                                <input type="text"  class="form-control" name="birthday" placeholder="yyyy/mm/dd">
                            </div>
                            {% if profileEditForm.errors and profileEditForm.birthday.errors %}
                                <div class="alert alert-danger" role="alert">
                                {% for error in profileEditForm.birthday.errors %}
                                  {{error}}
                                {% endfor %}<br>
                              </div>
                            {% endif %}
                          </div>

                          <div class="col mb-3">
                            <div class="form-group">
                              <label>{% trans "Meter Number" %}</label>
                                <input type="text"  class="form-control" name="meterNumber"  placeholder ="{{user.phone}}" disabled>
                            </div>
                            {% if profileEditForm.errors and profileEditForm.meterNumber.errors %}
                                <div class="alert alert-danger" role="alert">
                                {% for error in profileEditForm.meterNumber.errors %}
                                  {{error}}
                                {% endfor %}<br>
                              </div>
                            {% endif %}
                          </div>


                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col d-flex justify-content-end">
                        <button class="btn btn-warning" id="savingButt" type="submit" disabled>{% trans "Save Changes" %}</button>
                      </div>
                    </div>
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-12 col-md-3 mb-3">
        <div class="card mb-3">
          <div class="card-body">
            <div class="px-xl-3">
              <a href="{% url 'accounts:logout' %}"><button class="btn btn-block btn-secondary">
                <i class="fa fa-sign-out"></i>
                <span>{% trans "Logout" %}</span>
              </button>
            </a>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h6 class="card-title font-weight-bold">Support</h6>
            <p class="card-text">Get fast, free help from our friendly assistants.</p>
            <button type="button" class="btn btn-primary">Contact Us</button>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
</div>


    {% endblock content %}